cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED PROJECT_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT is required")
endif()
file(REAL_PATH "${PROJECT_ROOT}" _root)
file(STRINGS "${_root}/SOURCE-MANIFEST.sha256" _lines ENCODING UTF-8)
set(_paths)
string(TOLOWER "${_root}/" _prefix)
foreach(_line IN LISTS _lines)
    if(NOT _line MATCHES "^([0-9a-f]+)  (.+)$")
        message(FATAL_ERROR "Malformed source manifest entry")
    endif()
    set(_hash "${CMAKE_MATCH_1}")
    set(_path "${CMAKE_MATCH_2}")
    string(LENGTH "${_hash}" _length)
    string(TOLOWER "${_path}" _key)
    if(NOT _length EQUAL 64 OR IS_ABSOLUTE "${_path}" OR
       _path MATCHES "(^|/)\\.\\.?(/|$)|[\\\\:]" OR _key IN_LIST _paths)
        message(FATAL_ERROR "Unsafe or duplicate source path: ${_path}")
    endif()
    file(REAL_PATH "${_root}/${_path}" _file)
    string(TOLOWER "${_file}" _file_key)
    string(FIND "${_file_key}" "${_prefix}" _inside)
    if(NOT _inside EQUAL 0 OR NOT EXISTS "${_file}" OR IS_DIRECTORY "${_file}")
        message(FATAL_ERROR "Missing source or root escape: ${_path}")
    endif()
    file(SHA256 "${_file}" _actual)
    if(NOT _actual STREQUAL _hash)
        message(FATAL_ERROR "Source hash mismatch: ${_path}")
    endif()
    list(APPEND _paths "${_key}")
endforeach()
foreach(_required IN ITEMS cmakelists.txt src/plugin.cpp src/runtimeapi.cpp
        src/cloudmotionresolver.cpp extern/imgui/imgui.cpp config/vcpkg-source-lock.json)
    if(NOT _required IN_LIST _paths)
        message(FATAL_ERROR "Required universal source is missing: ${_required}")
    endif()
endforeach()
file(GLOB_RECURSE _files LIST_DIRECTORIES FALSE "${_root}/*")
foreach(_file IN LISTS _files)
    file(RELATIVE_PATH _path "${_root}" "${_file}")
    string(TOLOWER "${_path}" _key)
    if(NOT _key STREQUAL "source-manifest.sha256" AND NOT _key IN_LIST _paths)
        message(FATAL_ERROR "Unmanifested source input: ${_path}")
    endif()
endforeach()
list(LENGTH _paths _count)
message(STATUS "Verified complete source snapshot (${_count} files)")
